add Bookings
ElenaSsV/java-shareit pull request #4
Opened 2023-10-06 18:20 UTC by ElenaSsV

2023-10-07 13:20 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/RequestBookingDto.java
> +public class RequestBookingDto {
Dto суффикс не обязателен. T.е. когда нужно отличить Booking от BookingDto, то он нужен. А когда ты используешь наименование вида RequestBooking и ResponseBooking (что тоже очень распространено), то этого достаточно. Любой разработчик поймет что это обозначение объекта передающегося между слоями приложения (т.е. Dto). Резюмирую: или BookingDto или RequestBooking, а RequestBookingDto на мой взгляд уже перебор.  Из своей практики скажу что у нас предпочитают RequestBooking vs BookingDto, т.к. такое название более понятно системным аналитикам (они не знают про Dto, а Request осознать способны) и в документации к сервису RequestBooking выглядит лучше.

2023-10-07 13:31 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/RequestBookingDto.java
> +    private long id;
id лишнее поле

2023-10-07 13:33 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +    private long id;
более поняно если назвать bookingId

2023-10-07 13:41 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional(readOnly = true)
@Transactional(readOnly = true) лишнее - уже есть на классе. Значит автоматом есть на каждом методе класса.

2023-10-07 13:45 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Autowired
@Autowired перед конструктором можно не писать, и без него в текущей версии spring работает.

2023-10-07 14:07 UTC, VadimZharkov requested changes
Можно немного улучшить.

2023-10-07 20:16 UTC, ElenaSsV commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +    private long id;
Если переименовать, то тесты не проходят. Ожидается, что поле должно называться "id": 
pm.test("Test booking 'id' field", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData).to.have.property('id');

2023-10-08 13:32 UTC, VadimZharkov approved these changes

2023-10-13 11:39 UTC, merged